import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from 'next/link'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faBrain } from '@fortawesome/free-solid-svg-icons';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Modelo Preditivo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <nav className="flex justify-evenly items-center bg-zinc-900 p-2">
            
            <div className="">
              <Image src="/logo3.png" alt="logo" width={250} height={24}></Image>
            </div>

            <div className="">
              <div className="">
                <a href="/" className="text-base sm:text-lg md:text-xl lg:text-2xl xl:text-1xl text-slate-300 hover:text-sky-700 mr-4 text-xl">
                  Home
                </a>
                <a href="/profiles" className="text-base sm:text-lg md:text-xl lg:text-2xl xl:text-1xl text-slate-300 hover:text-sky-700 mr-4 text-xl">
                  Integrantes
                </a>
                <a href="/about" className="text-base sm:text-lg md:text-xl lg:text-2xl xl:text-1xl text-slate-300 hover:text-sky-700 text-xl">
                  Projeto
                </a>
              </div>
            </div>
          </nav>
        </header>
      {children}</body>
    </html>
  );
}