import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from 'next/link'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faBrain } from '@fortawesome/free-solid-svg-icons';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <nav className="flex items-center justify-between flex-wrap bg-sky-500 p-4">
            <div className="flex items-center flex-shrink-0 text-white mr-6">
              <Image src="/logo3.png" alt="logo" width={200} height={24}></Image>
            </div>
            <div className="w-full block flex-grow lg:flex lg:items-center lg:w-auto">
              <div className="text-sm lg:flex-grow">
                <a href="/" className="block mt-4 lg:inline-block lg:mt-0 text-sky-700 hover:text-white mr-4 text-xl">
                  Home
                </a>
                <a href="/profiles" className="block mt-4 lg:inline-block lg:mt-0 text-sky-700 hover:text-white mr-4 text-xl">
                  Integrantes
                </a>
                <a href="/about" className="block mt-4 lg:inline-block lg:mt-0 text-sky-700 hover:text-white text-xl">
                  Projeto
                </a>
              </div>
              <div>
                <a href="#" className="inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-teal-500 hover:bg-white mt-4 lg:mt-0">Download</a>
              </div>
            </div>
          </nav>
        </header>
      {children}</body>
    </html>
  );
}
